pyenv/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("resumes.urls")),
]

resumes/urls.py
from django.urls import path
from .views import home, new, show, edit, delete

app_name = "resumes"

urlpatterns = [
    path("", home, name="home"),
    path("new/", new, name="new"),
    path("<int:id>", show, name="show"),
    path("<int:id>/edit", edit, name="edit"),
    path("<int:id>/delete", delete, name="delete"),
]

resumes/models.py
from django.db import models


class Resume(models.Model):
    title = models.CharField(max_length=100)
    skill = models.CharField(max_length=100)
    content = models.TextField(null=True)


# Create your models here.

resumes/forms.py
from django.forms import ModelForm
from .models import Resume


class ResumeForm(ModelForm):
    class Meta:
        model = Resume
        fields = ["title", "skill", "content"]

resumes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ResumeForm
from .models import Resume


def home(request):
    if request.POST:
        resumes = ResumeForm(request.POST)
        resumes.save()
        return redirect("resumes:home")
    resumes = Resume.objects.all()
    return render(request, "resumes/home.html", {"resumes": resumes})


def new(request):
    resumes = ResumeForm()
    return render(request, "resumes/new.html", {"forms": resumes})


def show(request, id):
    resumes = get_object_or_404(Resume, id=id)
    if request.POST:
        forms = ResumeForm(request.POST, instance=resumes)
        forms.save()
        return redirect("resumes:home")
    return render(request, "resumes/show.html", {"resumes": resumes})


def edit(request, id):
    resumes = get_object_or_404(Resume, id=id)
    forms = ResumeForm(instance=resumes)
    return render(request, "resumes/edit.html", {"resumes": resumes, "forms": forms})


def delete(request, id):
    resumes = get_object_or_404(Resume, id=id)
    if request.POST:
        resumes.delete()
        return redirect("resumes:home")
    return render(request, "resumes/delete.html", {"resumes": resumes})


# Create your views here.

resumes/templates/resumes/delete.html
{% extends "shared/layout.html" %}{% block "content" %}

<form method="POST" action="">
  {%csrf_token%} <br />
  確認刪除？
  <button>確認</button>
</form>

<a href="{%url 'resumes:home'%}">返回</a>
{% endblock %}

resumes/templates/resumes/edit.html
{% extends "shared/layout.html" %}{% block "content" %}

<form method="POST" action="{% url 'resumes:show' resumes.id %}">
  {% csrf_token %}<br />
  {{ forms.as_p }}
  <br />
  <button>更新</button>
</form>
{% endblock %}

resumes/templates/resumes/home.html
{% extends "shared/layout.html" %}{% block "content" %}
<h1>履歷</h1>
<a href="{%url 'resumes:new'%}"> 新增履歷</a>
<ul>
  {% for resumes in resumes %}
  <li><a href="{%url 'resumes:show' resumes.id%}">{{resumes.title}}</a></li>
  {% endfor %}
</ul>

{% endblock %}

resumes/templates/resumes/new.html
{% extends "shared/layout.html" %}{% block "content" %}

<form method="POST" action="{%url 'resumes:home'%}">
  {% csrf_token %}<br />
  {{ forms.as_p }}
  <button>新增履歷</button>
</form>
{% endblock %}

resumes/templates/resumes/show.html
{% extends "shared/layout.html" %}{% block "content" %} {{resumes.title}}<br />
{{resumes.skill}} <br />
{{resumes.content}} <br />
<a href="{%url 'resumes:home'%}">返回</a>
<a href="{%url 'resumes:edit' resumes.id%}">編輯</a>
<a href="{%url 'resumes:delete' resumes.id%}">刪除</a>
{% endblock %}

templates/shared/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block "content" %}{% endblock %}
  </body>
</html>